# Generated by Django 4.1 on 2022-08-23 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'periodo',
                    models.CharField(
                        choices=[
                            ('M', 'Manhã'),
                            ('T', 'Tarde'),
                            ('N', 'Noite'),
                        ],
                        default='M',
                        max_length=1,
                    ),
                ),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='escola.aluno',
                    ),
                ),
                (
                    'curso',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='escola.curso',
                    ),
                ),
            ],
        ),
    ]
